### ISSUE TITLE
[TODO] Release 1.2

### ISSUE THREAD

**Issue by ljlamarche** [EarthCubeInGeo/resen-core#28]
- [x] Propagate the changes that were made on the resen-core built on the server pre-CEDAR to the released resen-core
- [ ] Write unit tests
- [ ] Implement style guidelines ([linter](https://code.visualstudio.com/docs/python/linting)/[pylint](https://www.pylint.org/))
- [ ] Set up Continuous Integration Testing
- [x] Optimize resen-core/remove conda
- [x] Add one more tutorial with a summary of geospace packages included in resen-core and where users can go for more information
- [x] Include tutorials with resen-core
- [x] add some new geospace python packages (pydarn, etc.)

**Comment by asreimer** [comment]
We are punting a few of these things to a later release in the interest of getting a 1.0 out there.

**Comment by asreimer** [comment]
With #41, we've finished the tutorials.

**Comment by asreimer** [comment]
Do we want to also move the location of installed python packages and then have the venvs exist `/home/jovyan/work`? This would make it consistent with the server, allowing for persistent virtual environments.
