### ISSUE TITLE
[TODO] Release 1.1

### ISSUE THREAD

**Issue by asreimer** [EarthCubeInGeo/resen-core#43]
- [x] add new packages (https://github.com/EarthCubeInGeo/resen-core/issues/42)
- [x] remove davitpy (doesn't work, community wants people to use pydarn) (@ljlamarche)
- [x] add readthedocs page for resen-core (https://github.com/EarthCubeInGeo/resen-core/issues/4 @pmreyes2)
- [ ] improve documentation (https://github.com/EarthCubeInGeo/resen-core/issues/40)
- [x] check if this is still an issue: https://github.com/EarthCubeInGeo/resen-core/issues/7

Aiming for 5 June release.
